source 'https://rubygems.org'
gem 'sinatra'
gem 'pony'
gem 'sinatra-flash'
gem 'heroku'
gem 'asset_sync', git: 'git://github.com/rumblelabs/asset_sync.git', branch: 'sinatra'
gem 'sinatra-static-assets'
